package com.example.silentguardian.ui.gallery

import android.app.AlertDialog
import android.content.Context
import android.graphics.Color
import android.net.Uri
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.BaseAdapter
import android.widget.ImageView
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.fragment.app.Fragment
import com.example.silentguardian.MainActivity
import com.example.silentguardian.databinding.FragmentGalleryBinding
import org.json.JSONArray

class GalleryFragment : Fragment() {

    private var _binding: FragmentGalleryBinding? = null
    private val binding get() = _binding!!
    private val imageUris = mutableListOf<Uri>()

    private val pickMedia = registerForActivityResult(ActivityResultContracts.GetContent()) { uri: Uri? ->
        uri?.let {
            imageUris.add(it)
            saveImagesToVault()
            // IMPORTANT: Force the activity cast to see if it's failing
            val mainAct = activity as? MainActivity
            if (mainAct != null) {
                mainAct.addSecurityLog("MEDIA_IMPORTED")
            } else {
                android.util.Log.e("VaultError", "Could not find MainActivity to log event")
            }
            (binding.galleryGrid.adapter as? ImageAdapter)?.notifyDataSetChanged()
        }
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
        _binding = FragmentGalleryBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        loadImagesFromVault()

        // Use the camelCase name generated by ViewBinding
        binding.galleryGrid.adapter = ImageAdapter()

        binding.btnImportMedia.setOnClickListener {
            pickMedia.launch("image/*")
        }

        binding.galleryGrid.setOnItemLongClickListener { _, _, position, _ ->
            AlertDialog.Builder(requireContext())
                .setTitle("Purge Media")
                .setMessage("Permanently remove this entry?")
                .setPositiveButton("Purge") { _, _ ->
                    imageUris.removeAt(position)
                    saveImagesToVault()
                    (activity as? MainActivity)?.addSecurityLog("MEDIA_PURGED")
                    (binding.galleryGrid.adapter as ImageAdapter).notifyDataSetChanged()
                }
                .setNegativeButton("Cancel", null)
                .show()
            true
        }
    }

    private fun saveImagesToVault() {
        val sharedPref = requireActivity().getSharedPreferences("SilentGuardianVault", Context.MODE_PRIVATE)
        val jsonArray = JSONArray()
        imageUris.forEach { jsonArray.put(it.toString()) }
        sharedPref.edit().putString("gallery_uris", jsonArray.toString()).apply()
    }

    private fun loadImagesFromVault() {
        val sharedPref = requireActivity().getSharedPreferences("SilentGuardianVault", Context.MODE_PRIVATE)
        val jsonString = sharedPref.getString("gallery_uris", "[]")
        val jsonArray = JSONArray(jsonString ?: "[]")
        imageUris.clear()
        for (i in 0 until jsonArray.length()) {
            imageUris.add(Uri.parse(jsonArray.getString(i)))
        }
    }

    inner class ImageAdapter : BaseAdapter() {
        override fun getCount(): Int = imageUris.size
        override fun getItem(position: Int): Any = imageUris[position]
        override fun getItemId(position: Int): Long = position.toLong()

        override fun getView(position: Int, convertView: View?, parent: ViewGroup?): View {
            val imageView = (convertView as? ImageView) ?: ImageView(context).apply {
                layoutParams = ViewGroup.LayoutParams(350, 350)
                scaleType = ImageView.ScaleType.CENTER_CROP
                setPadding(8, 8, 8, 8)
                setBackgroundColor(Color.parseColor("#1A1A2E"))
            }
            try {
                imageView.setImageURI(imageUris[position])
            } catch (e: Exception) {
                imageView.setImageResource(android.R.drawable.ic_menu_gallery)
            }
            return imageView
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}